#!/usr/bin/env python3
"""Generate contract_constants.hpp from xl300-dds-v2's config/dds_domain.yaml +
config/topic_registry.yaml -- the "contract facts" (domain id, topic name
strings, QoS profile names, partition names) that must be identical across
every app on the bus, as opposed to genuinely per-deployment config (transport
host/port, debug level, publish_interval_ms).

Deliberately stdlib-only (no PyYAML) so this runs inside
umeshwalkar/xl300-dev-base:0.1.0 without adding a new toolchain dependency --
both source files have a simple, flat 2-level structure well within what a
small hand-rolled parser can handle correctly; this is NOT a general YAML
parser and will mis-parse anything fancier (multi-line strings, anchors, flow
style). If topic_registry.yaml ever needs those, switch to PyYAML instead of
extending this script.

Usage: gen_contract_constants.py <dds_domain.yaml> <topic_registry.yaml> <out.hpp>
"""
import re
import sys


def strip_comment(line: str) -> str:
    # Naive but sufficient here: none of our values legitimately contain '#'.
    idx = line.find('#')
    return line if idx < 0 else line[:idx]


def parse_domain_id(path: str) -> int:
    with open(path, encoding='utf-8') as f:
        for raw in f:
            line = strip_comment(raw)
            m = re.match(r'\s*domain_id:\s*(\d+)\s*$', line)
            if m:
                return int(m.group(1))
    raise SystemExit(f"FATAL: no 'domain_id:' found in {path}")


def parse_topics(path: str) -> list[dict]:
    """Returns a list of {'topic': str, 'type': str, 'qos': str, 'partition': str}.
    Skips entries missing any of these four required fields entirely (e.g. a
    malformed entry) rather than emitting a partially-populated constant."""
    topics = []
    current = None
    with open(path, encoding='utf-8') as f:
        for raw in f:
            line = strip_comment(raw).rstrip()
            if not line.strip():
                continue
            # Top-level topic key: exactly 2-space indent, ends with ':' alone
            # (no inline value) -- e.g. "  sensors/ctd:"
            m = re.match(r'^  (\S+):\s*$', line)
            if m:
                if current is not None:
                    topics.append(current)
                current = {'topic': m.group(1)}
                continue
            # Property line: 4-space indent, "key: value" -- e.g. "    qos: SENSOR"
            m = re.match(r'^    (\w+):\s*(.+?)\s*$', line)
            if m and current is not None:
                key, value = m.group(1), m.group(2)
                value = value.strip('"')  # a few values (publisher) are quoted
                current[key] = value
    if current is not None:
        topics.append(current)

    required = ('topic', 'type', 'qos', 'partition')
    return [t for t in topics if all(k in t for k in required)]


def cpp_identifier(topic: str) -> str:
    """'sensors/ctd' -> 'SensorsCtd', 'health/<node>' -> 'Health' (the <node>
    placeholder segment is dropped, not transliterated -- it's a templating
    marker in the topic name, not a real path segment)."""
    parts = [p for p in topic.split('/') if p and p != '<node>']
    words = []
    for p in parts:
        alnum = re.sub(r'[^0-9a-zA-Z]', ' ', p)
        words.extend(w.capitalize() for w in alnum.split())
    return 'k' + ''.join(words)


def render(domain_id: int, topics: list[dict]) -> str:
    lines = []
    lines.append('#pragma once')
    lines.append('// GENERATED by uuv_interfaces/gen_contract_constants.py from')
    lines.append('// xl300-dds-v2/config/dds_domain.yaml + config/topic_registry.yaml.')
    lines.append('// DO NOT EDIT BY HAND -- fix the source YAML in xl300-dds-v2, bump the')
    lines.append('// submodule, and re-run gen.sh.')
    lines.append('//')
    lines.append('// These are CONTRACT FACTS -- domain id, topic name strings, QoS profile')
    lines.append('// names, partition names -- that must be identical for every participant')
    lines.append('// on the bus. They do not belong in a per-app JSON config file where a')
    lines.append("// typo could silently desync one app from everyone else's understanding")
    lines.append('// of the topic. Genuinely per-deployment settings (transport host/port,')
    lines.append('// debug level, publish_interval_ms) still belong in each app\'s own config.')
    lines.append('')
    lines.append('namespace xl300::contract {')
    lines.append('')
    lines.append(f'constexpr int kDomainId = {domain_id};')
    lines.append('')
    lines.append('struct TopicInfo {')
    lines.append('    const char* topic;')
    lines.append('    const char* type;')
    lines.append('    const char* qos_profile;')
    lines.append('    const char* partition;')
    lines.append('};')
    lines.append('')
    lines.append('namespace topics {')
    seen_names = set()
    for t in topics:
        ident = cpp_identifier(t['topic'])
        if ident in seen_names:
            raise SystemExit(
                f"FATAL: two topics both map to identifier '{ident}' "
                f"(collision on '{t['topic']}') -- extend cpp_identifier() to disambiguate")
        seen_names.add(ident)
        lines.append(
            f'    constexpr TopicInfo {ident} = '
            f'{{ "{t["topic"]}", "{t["type"]}", "{t["qos"]}", "{t["partition"]}" }};'
        )
    lines.append('} // namespace topics')
    lines.append('')
    lines.append('} // namespace xl300::contract')
    lines.append('')
    return '\n'.join(lines)


def main() -> None:
    if len(sys.argv) != 4:
        print(__doc__, file=sys.stderr)
        raise SystemExit(2)
    domain_yaml, topics_yaml, out_path = sys.argv[1:4]

    domain_id = parse_domain_id(domain_yaml)
    topics = parse_topics(topics_yaml)
    if not topics:
        raise SystemExit(f"FATAL: parsed zero topics from {topics_yaml} -- parser bug or empty file")

    with open(out_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(render(domain_id, topics))
    print(f"[gen_contract_constants] domain_id={domain_id} topics={len(topics)} -> {out_path}")


if __name__ == '__main__':
    main()
